# Generated by Django 2.2.4 on 2019-11-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='audience',
        ),
    ]
