# Generated by Django 2.2.7 on 2019-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191128_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_path',
            field=models.TextField(),
        ),
    ]
